default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: pets_portal_development

test:
  <<: *default
  database: pets_portal_test

production:
  <<: *default
  database: pets_portal_production
  username: <%= ENV['PETS_PORTAL_USERNAME'] %>
  password: <%= ENV['PETS_PORTAL_DATABASE_PASSWORD'] %>
